### ISSUE TITLE
Комментарий к стилю кода

### ISSUE THREAD

**Issue by amidovitch** [GudveN/School-Database#1]
Минусы:
1. Названия событий о нажатии на кнопки не говорят о тех функциях, которые должны выполнятся ими.
2. Некоторые большие функции вынесены в отдельные классы.
3. Структура организации файлов очень громоздкая

Плюсы:
1. Читаемость кода (соблюдены табуляции, понятные названия переменных и функций).
2. Код класса разбит на cpp и header файлы.

**Comment by amidovitch** [comment]
Э, вы че там, исправлять будете?

**Comment by GudveN** [comment]
1.	Переименовал события нажатия кнопок на более подходящие.
2.	Распределил все функции в нужные cpp файлы.
3.	Сократил количество файлов за счёт удаления ненужных и пустых cpp файлов.
